language: python
python:
  - "2.7"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
# command to install dependencies
virtualenv:
  system_site_packages: true
before_install:
   #Uses miniconda installation of scientific python packages instead of building from source
   #or using old versions supplied by apt-get. Source: https://gist.github.com/dan-blanchard/7045057
   - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh; fi
   - chmod +x miniconda.sh
   - ./miniconda.sh -b
   - export PATH=/home/travis/miniconda3/bin:/home/travis/miniconda2/bin:$PATH
   - conda update --yes conda
   - conda config --add channels conda-forge
   - conda config --add channels defaults
   - conda config --add channels r
   - conda config --add channels bioconda
   - sudo apt-get update -qq
   - sudo apt-get install -qq build-essential libgsl0-dev bedtools mummer
   - "export DESMANHOME=$TRAVIS_BUILD_DIR"
   - "export DISPLAY=:99.0"
   - "sh -e /etc/init.d/xvfb start"
   - curl -fsSL https://cloudstor.aarnet.edu.au/plus/index.php/s/7DH5qMuM5jMbcUc/download > testdata.tar
   - tar xf testdata.tar
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION cython numpy scipy biopython pandas pip scikit-learn docutils sphinx jinja2 seaborn nextflow bwa samtools
  - python setup.py install
# command to run tests
script: ./scripts/desmanflow.nf --speciescontigs=testdata/species_contigs.txt --assembly=testdata/testasm.fa --inputreads=testdata/fastq

branches:
  only:
    - travis_desmanflow
